CREATE TABLE IF NOT EXISTS users(
    id SERIAL,
    email VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    active BOOLEAN NOT NULL
);
ALTER TABLE users ADD CONSTRAINT users_id PRIMARY KEY(id);

CREATE TABLE IF NOT EXISTS comments(
    id SERIAL,
    postId INTEGER NOT NULL,
    authorId INTEGER NOT NULL,
    text VARCHAR NOT NULL
    timestamp TIMESTAMP NOT NULL
);
ALTER TABLE comments ADD CONSTRAINT comments_id PRIMARY KEY(id)
ALTER TABLE comments ADD CONSTRAINT comments_post_id FOREIGN KEY(posts_id) REFERENCES posts(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE comments ADD CONSTRAINT comments_author_id FOREIGN KEY(users_id) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS posts(
    id SERIAL,
    authorId INTEGER NOT NULL,
    text VARCHAR,
    image VARCHAR,
    timestamp TIMESTAMP NOT NULL
);
ALTER TABLE posts ADD CONSTRAINT posts_id PRIMARY KEY(id);
ALTER TABLE posts ADD CONSTRAINT posts_author_id FOREIGN KEY(users_id) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE CASCADE;